### PR TITLE
Added the About US page with some Basic FAQS

### PR DESCRIPTION
**Pull request by Ritesh2351235**
This PR introduces an "About Us" page to the QuizMaster application, enhancing user experience and providing important information about our platform. The page includes a comprehensive description of QuizMaster and its features, emphasizing our commitment to interactive learning and user engagement.

Additionally, an FAQ section has been added to address common questions from users. This section provides clear answers to queries related to quiz creation, performance tracking, password resets, and collaboration features.

Changes Made:

Created the "About Us" section with a detailed description of QuizMaster.
Added an FAQ section, including six common questions and answers to assist users.
Styled both sections for improved readability and visual appeal.
Screenshot 2024-10-02 142955
Screenshot 2024-10-02 143032

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@Ritesh2351235 Nice work

**Comment by vishalverma9572** [comment]
@Ritesh2351235 But This page will not be added to the dashboard. It should be on the Home or Landing page. Correct that, and then I'll merge it. Also, try to make the UI more attractive if possible.

**Comment by Ritesh2351235** [comment]
@vishalverma9572 Vishal ill just add this page on the landing page and for the UI part I think we need to standardize some basic CSS components so that everybody's code aligns. It's just a cleaner way to do it.

**Comment by vishalverma9572** [comment]
@Ritesh2351235 Yup👍, Sounds good...

so create a new PR I am closing this one. Is this fine?

**Comment by Ritesh2351235** [comment]
@vishalverma9572 can you assign me the 
- #3
So that I could work on that with the new PR

**Comment by vishalverma9572** [comment]
create a new one

**Pull request closed without merging**
