### PR TITLE
Feature/zod input validation

### LINKED ISSUE #32: Implement proper input validation at backend
The backend of this application currently lacks comprehensive input validation, which could lead to invalid or unsafe data being processed and stored in the database. To enhance the application's robustness, we need to implement input validation across various endpoints using libraries such as **Zod**

#### Tasks:
1. **Identify Inputs**: Review all API endpoints to identify inputs that require validation, including but not limited to user registration, login, and other APIs, etc.
2. **Implement Zod Validation**: 
    - Define Zod schemas for input validation, ensuring that all required fields are validated with appropriate data types, length constraints, and custom error messages.
    - Integrate these validation schemas into the backend service logic, rejecting requests with invalid data.
3. **Error Handling**: Ensure proper error handling by providing descriptive validation error responses to the client in case of invalid inputs.

#### Expected Outcome:
- Input validation is implemented across the backend using Zod.
- Invalid requests are rejected with meaningful error messages.
- The backend is more resilient to faulty or malicious inputs.

### PR DESCRIPTION
**Pull request by PorePranav**
This pull request introduces input validation for various user-related actions and quiz functionalities in the backend using **Zod**. The following validation schemas have been created to ensure that the input data adheres to specified formats and constraints, enhancing the robustness of the application.

Fixes #32 

#### Changes Made:

1. **User Registration**:
    - `registrationSchema`: Validates username, email, and password with requirements for minimum/maximum lengths and formats.

2. **User Login**:
    - `loginSchema`: Validates the presence of a valid email and password.
    
3. **Username and Password Update**:
    - `updateUsernameSchema`: Ensures that the username follows the specified length constraints.
    - `updatePasswordSchema`: Validates the password with required constraints.

4. **Password Reset Request**:
    - `requestPasswordResetSchema`: Validates that the provided email is in the correct format.

5. **Quiz Functionality**:
    - `questionSchema`: Validates the question text, options, and the correct answer, ensuring at least two options are provided.
    - `quizSchema`: Validates the title, questions (ensuring at least one), and time limit for the quiz.
    - `questionUpdateSchema` and `quizUpdateSchema`: Allow optional updates to questions and quizzes while maintaining necessary constraints where applicable.
#### Benefits:
- Improves data integrity and security by ensuring that only valid data can be processed.
- Provides clear error messages for invalid inputs, enhancing user experience.
- Facilitates easier maintenance and readability of the validation logic.
#### Additional Notes:
- The Zod library was used for its simplicity and type safety, making it easier to manage validation schemas.

Please review the changes and let me know if there are any questions or further modifications needed.

### CODE REVIEW

**Comment by PorePranav** [comment]
PR #35 adds Zod validation for better schema validation and error handling.

**Comment by vishalverma9572** [comment]
image
the response should be like this but your response is this
image

if I will merge this this will create lots of issues in current scenerio please send me req and res formats for login and register then I will merge it if it looks good...

**Comment by vishalverma9572** [comment]
and we are sending json as response not html

**Comment by vishalverma9572** [comment]
create new PR after resolving this issues. Thanks for your valuable efforts. I am expecting a good PR soon...
I am closing this one

**Pull request closed without merging**
