### PR TITLE
(fix)added user still exists feature in auth middleware

### PR DESCRIPTION
**Pull request by Aditya-NV-06**
I made changes on the auth middleware mentioned by the issue #19 .

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@Aditya-NV-06 , please clarify what  are the issues you are resolving. and resolve merge conflicts

**Comment by Aditya-NV-06** [comment]
I can't see any problem with code .

**Comment by vishalverma9572** [comment]
@Aditya-NV-06 
image
image
These are the merge conflicts I am facing. Please resolve them. If you encounter any issues while resolving or are unsure how to do it, feel free to take help from YouTube or the community.

**Comment by vishalverma9572** [comment]
@Aditya-NV-06, Please don't hesitate to ask for help if needed. Looking forward to the corrected PR soon."

**Comment by Aditya-NV-06** [comment]
Ok but I can't resolve the merge conflict.
It is very new to me.

**Comment by vishalverma9572** [comment]
@Aditya-NV-06 , Yeah, go ahead and give it a try! Let me know if you need any assistance. It’s easy—you just need to give it some time.

**Pull request closed without merging**
