### PR TITLE
feat: Improve backend in controller

### PR DESCRIPTION
**Pull request by Wasif0787**
- Divided the router and controllers for code reusability

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@Wasif0787, have you tested the backend? Is it working fine?

**Comment by Wasif0787** [comment]
there are no package,json in frontend so i havent chacked , could you please check it

**Comment by vishalverma9572** [comment]
@Wasif0787 please check carefully or download again because on GitHub there is package .json

**Comment by Wasif0787** [comment]
I have checked the backend it working fine and there is no package.json in frontned folder check carefully

**Comment by vishalverma9572** [comment]
@Wasif0787 Thanks for your Contribution! , Do checkout other issues...

**Pull request merged**
