### PR TITLE
Added User guide at home page also gave margins between components of user guide

### PR DESCRIPTION
**Pull request by Sanchitagarwal7**
WhatsApp Image 2024-10-03 at 15 07 44
WhatsApp Image 2024-10-03 at 15 07 58
WhatsApp Image 2024-10-03 at 15 08 27

### CODE REVIEW

**Comment by Sanchitagarwal7** [comment]
See to it if it looks as intended @vishalverma9572

**Comment by vishalverma9572** [comment]
@Sanchitagarwal7 please style homepage buttons in mobile view, So it looks good! it will take few lines of code then I will merge this.

**Comment by vishalverma9572** [comment]
@Sanchitagarwal7  I am not closing this PR, include your next commit in the Same PR

**Review by vishalverma9572 — CHANGES_REQUESTED** [review]
responsiveness

**Comment by Sanchitagarwal7** [comment]
WhatsApp Image 2024-10-04 at 12 47 56
WhatsApp Image 2024-10-04 at 12 48 10


added @media for small screen in home.css to make them a bit better @vishalverma9572

**Pull request merged**
