### PR TITLE
Changed the UI of the Home page

### PR DESCRIPTION
**Pull request by khushiiagrawal**
## Changed the UI of the HOME PAGE

- Updated **background** to a linear gradient for a more dynamic and attractive look.
- Increased **logo size** and added a **pulse animation** with drop-shadow.
- Enhanced **typography** by increasing font sizes, weight, and adding text shadow for better readability.
- Improved **button design** with rounded corners, larger size, and hover animations for better interactivity.
- Adjusted **secondary button styles** with larger size and improved hover effects.

### CODE REVIEW

**Comment by vishalverma9572** [comment]
Looks good, but the About Us page was recently added. Please include that as well.


image

Pull the latest changes first, and then create the PR

**Comment by khushiiagrawal** [comment]
The changes have been made and lastly the landing page looks like this 

https://github.com/user-attachments/assets/b8bbc84b-3035-4632-ba60-e31102854e12

**Comment by vishalverma9572** [comment]
@khushiiagrawal your Pr is merged Successfully. Thanks for your valuable contribution. Do checkout other issues as well...

**Comment by khushiiagrawal** [comment]
@vishalverma9572 please add the label to the merged pr as hactoberfest-accepted

**Pull request merged**
