### PR TITLE
Add old password field to profile page

### PR DESCRIPTION
**Pull request by TommiNICE**
This pull request adds a new field for the old password on the profile page. It also includes validation to check if the old password matches the user's current password before allowing them to update their password.

### CODE REVIEW

**Review by vishalverma9572 — COMMENTED** [review]
@TommiNICE  , have you tested this? If yes, please attach some images of the frontend. I couldn't find any issues in your code, but just to be sure, I'm asking for pictures because you haven't added the old password input in the same div. That's why I want to see how it's looking in all test cases.
image

**Comment by vishalverma9572** [comment]
@TommiNICE  and resolve merge conflicts..
Expecting a PR soon...

**Comment by TommiNICE** [comment]
Hi @vishalverma9572,
Here are screenshots for the test cases:
1. Test case: Invalid old password:
iScreen Shoter - Google Chrome - 241004113638

2. Test case: Empty password field:
iScreen Shoter - Google Chrome - 241004114615

3. Test case: Password update succesful:
iScreen Shoter - Google Chrome - 241004114502

Concerning the testing, I would like to add end-to-end testing with Cypress. I would raise a separate issue for it.

About the div element, I checked it. I think it belongs there, because the other two input elements are children of the same div, that I use for input field.

But now I have the problem, that I do not know exactly how to solve the merge confilcts. Can you help me? Gonna ask dicsord too.

**Comment by vishalverma9572** [comment]
@TommiNICE, Wonderful contribution! Just a merge conflict ahead. Please resolve it, and as soon as it's done, I'll merge it.

**Comment by vishalverma9572** [comment]
@TommiNICE , It's a bit complex, and I can't resolve it in the web editor. That's why I'm asking for your help. Once you resolve it, I'll merge it.

**Comment by TommiNICE** [comment]
Hi @vishalverma9572, I solved the conflict. So it is ready for merge 😃

**Comment by vishalverma9572** [comment]
@TommiNICE ,merged! Thanks for your contribution.Do checkout other issues as well. Expecting more PR from your side

**Pull request merged**
