### PR TITLE
Fixed the reset password flow

### PR DESCRIPTION
**Pull request by ash956901**
# Issue no . 103

@vishalverma9572 sir the email functionality works good in the local dev enviorenment, i would recommend you replacing the mail pass in the production platform of backend , and check the mail credentials one time .

but even after it there was another issue in the local dev enviorenment after the mail which was the reset password saying invalid token , which i have fixed now. Heres the screenshot.

Screenshot 2024-10-11 at 7 44 30 PM

For the mail issue , recheck ur env in the production platform rest i have fixed the reset password flow .Glad to work with you . It is really a great platform.

### CODE REVIEW

**Comment by ash956901** [comment]
@vishalverma9572 could u please merge this pr before midnight? it would be of huge help...

**Comment by ash956901** [comment]
@vishalverma9572 could u please merge this pr ?

**Comment by vishalverma9572** [comment]
@ash956901, It looks like you've created the PR, but it may not include all your commits. In your latest commit, only one line of code was added. Please check if all relevant commits are pushed to the branch before making the PR. You can reattach any missing commits to ensure everything is included.

**Comment by ash956901** [comment]
@vishalverma9572  The commit is there, the main issue lies in your misconfiguration of the env file of production in the backend ig of smtp, which is the main issue i have pointed out and i cant fix that by myself, rest there was only one line to add to fix the flow , thats what i figured , you can update the smtp credentials and merge this pr your reset password flow will be on the go

**Pull request merged**
