### PR TITLE
Added the User Guide Page with interative buttons for quick scrolling

### PR DESCRIPTION
**Pull request by Sanchitagarwal7**
WhatsApp Image 2024-10-03 at 13 38 18
WhatsApp Image 2024-10-03 at 13 38 39

### CODE REVIEW

**Comment by Sanchitagarwal7** [comment]
Please authorize it, if it looks fine @vishalverma9572

**Comment by vishalverma9572** [comment]
@Sanchitagarwal7  I am merging this PR & it really looks well described.

**Comment by Sanchitagarwal7** [comment]
Thank you for the opportunity, had fun with this

**Comment by vishalverma9572** [comment]
@Sanchitagarwal7, , I need another favor from you. Could you integrate this page to be accessible from the Home page as well? New users might need help without logging in. Also, please add a little bit of margin between the components on the User Guide page.

expecting another PR soon...

**Comment by Sanchitagarwal7** [comment]
Yes, of course

**Pull request merged**
