### PR TITLE
Added the About US and FAQ section in the Home Page 

### PR DESCRIPTION
**Pull request by Ritesh2351235**
This PR introduces an "About Us" page to the QuizMaster application, enhancing user experience and providing important information about our platform. The page includes a comprehensive description of QuizMaster and its features, emphasizing our commitment to interactive learning and user engagement.
Changes Made:
- Added an About Us button on the Home Page
- Added the About Us with FAQ's on another page with routing
- Maintained the Loader for seamless routing
- Made considerable changes in UI/UX

Screenshot 2024-10-02 154944
Screenshot 2024-10-02 155019

Screenshot 2024-10-02 154918

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@Ritesh2351235   , I've checked it, and there is an issue. After clicking the About Us button on the Home page, it redirects to /login. I think this is because you haven't specified what to render on this route in App.js

**Comment by Ritesh2351235** [comment]
@vishalverma9572  Ia
Screenshot 2024-10-02 165752
m not getting this problem when running it locally 
the route has been correctly routed to /about-us

**Comment by Ritesh2351235** [comment]
@vishalverma9572 i have figured out the problem i will be making the changes soon

**Comment by vishalverma9572** [comment]
@Ritesh2351235 , yes, I'm expecting a PR soon

**Comment by Ritesh2351235** [comment]
@vishalverma9572 hey vishal i have fixed the above after can you just verify

**Comment by vishalverma9572** [comment]
@Ritesh2351235  merged! Thanks for your contribution. Please continue with other issues, or you can enhance the About Us page by adding some logos, pictures, popups   etc., to make it more dynamic.

**Pull request merged**
