### PR TITLE
Enhanced the UI/UX of the users guide page

### PR DESCRIPTION
**Pull request by gt951436**
Issue number: #135 

- Changed the background color to match the theme of the application.
- Horizontally aligned the buttons present under the Table of contents.
- Added transition to the above buttons while hovering over them.
- Text UI enhancement.
- Added functionality of redirection to the Home page when clicked on "Quizmaster".

-Proof of work :
Screenshot 2024-10-16 234259
Screenshot 2024-10-16 234741

### CODE REVIEW

**Comment by gt951436** [comment]
@vishalverma9572  please review this PR.

**Comment by gt951436** [comment]
@vishalverma9572 would you please review this PR?

**Comment by vishalverma9572** [comment]
@gt951436, everything is looking good but please use theme colors and background color.

**Comment by vishalverma9572** [comment]
@gt951436 , please make changes and let me know when it's done

**Comment by gt951436** [comment]
@vishalverma9572  i have created a new PR as #163 , review that one and you can remove this(#140 ) one.

**Pull request closed without merging**
