### PR TITLE
Revert "Feat: Implemented Tailwind CSS in 4 components"

### PR DESCRIPTION
**Pull request by vishalverma9572**
Reverts vishalverma9572/QuizMaster#65

you have revealed some of your api keys in firebase.js that's why I have to revert this PR and I am closing this too lease create a new one
Screenshot 2024-10-05 020319

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@Sanchitagarwal7, I would suggest you to change those api keys asap!

**Comment by Sanchitagarwal7** [comment]
Hey @vishalverma9572 do you want me to make the change?

**Comment by vishalverma9572** [comment]
@Sanchitagarwal7 yeah!

**Comment by Sanchitagarwal7** [comment]
Its not my api key, i didnt change the backend but i will surely do as instructed 🫡

**Pull request merged**
