### PR TITLE
enhancement/improved the middleware authjs file

### PR DESCRIPTION
**Pull request by ugz-man**
### Improvements made were:
 - [x]  Check if the user still exists
 - [x] Checking if the user recently changed password after the token was issued
 - [x] Added the already logged in user on request object for easy access down the middleware pipeline

Made changes to the user router, user controller and user model files.

### CODE REVIEW

**Comment by ugz-man** [comment]
@vishalverma9572 I think part of these errors are occurring because there is only a branch currently `main branch` and making a pull request will try to merge with it, I suggest creating another branch where we can make a pull request to like a `dev branch`, which can then be merged with the `main branch` by a member of the team.

**Comment by vishalverma9572** [comment]
@ugz-man, , I've created a dev_branch from the main branch. You can now work on that, and if it looks good, I'll merge it into the main branch.
And I'm closing this PR. Please create a new one on the dev_branch.

**Comment by vishalverma9572** [comment]
@ugz-man ,  if you want I can make you maintainer of that branch for some time

**Comment by ugz-man** [comment]
@vishalverma9572 Thank you very much for the opportunity, but I really can't handle a task like that right now, Thank you very much.

**Pull request closed without merging**
