### PR TITLE
feature: added zod input validation + fixed merge conflicts

### PR DESCRIPTION
**Pull request by PorePranav**
I have fixed the merge conflicts, please merge this PR, let me know if there are any changes to make! Thanks.

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@PorePranav , i also want to merge this PR but there are issues. And I appreciate your efforts. While working on this in the meantime you can create PR on other issues as well I will merge those.

**Comment by PorePranav** [comment]
> @PorePranav , I tried to link your code with frontend but it didn't worked. And you can see your deployed link and test those routes at https://quiz-master-backend-git-fork-por-dec0fe-vishal-kumar-s-projects.vercel.app/
> 
> and actual backend is deployed at [https://quiz-master-backend-six.vercel.app/api](https://quiz-master-backend-six.vercel.app/) you can test both and work to resolve this & update me ASAP!

As I currently don't have access to the deployed frontend, I am not able to pinpoint the issue, but everything is working flawlessly locally. I have changed the code a bit to improve the validation. Please check and confirm once.

Thank you!

**Comment by vishalverma9572** [comment]
@PorePranav, I have accepted your access request.

**Comment by PorePranav** [comment]
> @PorePranav, I have accepted your access request.

image
image
image
image


Seems to be working fine on the preview deployment, can you please confirm once?

**Comment by vishalverma9572** [comment]
@PorePranav , Thanks for your wonderful contribution! Since you've made some changes to the tech stack, I would kindly request you to update the backend documentation accordingly. That will also count towards your Hacktoberfest contribution.

**Pull request merged**
