### PR TITLE
Enhanced the UI/UX of the users guide page and appropriate theme, background color scheme.

### PR DESCRIPTION
**Pull request by gt951436**
## Pull Request Title
 issue number - #135 

Enhanced the UI/UX of the users guide page and appropriate theme, background color scheme.

## Description

- Changed the background color to match the theme of the application.
- Horizontally aligned the buttons present under the Table of contents.
- Added transition to the above buttons while hovering over them.
- Text UI enhancement.
- Added functionality of redirection to the Home page when clicked on "Quizmaster".

- closes - #135 

## Screenshots (if applicable)
Screenshot 2024-10-19 174330

### CODE REVIEW

**Comment by gt951436** [comment]
@vishalverma9572 please review this PR, i have updated the themes and background as per the application theme.

**Comment by gt951436** [comment]
@vishalverma9572 would you please review this PR?

**Comment by gt951436** [comment]
@vishalverma9572 please review the PR.

**Comment by vishalverma9572** [comment]
@gt951436,Thanks for your contribution. I was a bit busy this time, which is why the review took longer than usual. Please feel free to work on other issues as well. I'm looking forward to seeing another PR from you soon!

**Comment by gt951436** [comment]
@vishalverma9572 it's alright, thanks.

**Pull request merged**
