### PR TITLE
Feat: Implemented Tailwind CSS in 4 components

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
Replaced the CSS files with Tailwind CSS for styling in the following four components:
- Authorisation Page
- Forgot Password
- Reset Password
- About Us Page

### CODE REVIEW

**Comment by vishalverma9572** [comment]
@Sambit-Mondal, I've been facing some issues after deploying this PR; the screen is blank. Do you know why this might be happening? Also, could you check if you can see a preview? Please attach some pictures so I can visualize how it looks.

**Comment by Sambit-Mondal** [comment]
@vishalverma9572 It may be occuring because you may have not initialised the Firebase part yet. That's why the screen might be turning completely blank.

I've mistakenly committed the Firebase (Social part) auth too in this branch. Just give me some time. I'll remove it and let you know.

Sorry again for the unintentional mistake.

**Comment by vishalverma9572** [comment]
@Sambit-Mondal, No need to say sorry, you're working on a tough task, and unintentional results happen. Looking forward to your PR soon. Thanks again for your valuable contribution!"

**Comment by Sambit-Mondal** [comment]
@vishalverma9572 I've resolved the issue and pushed the changes. Kindly do check!

**Comment by vishalverma9572** [comment]
@Sambit-Mondal Great! I'm glad it worked out. Thank you for your patience, and I'll be looking forward to those API keys whenever you have the time. Let me know if there's anything else you'd like assistance with!

**Comment by vishalverma9572** [comment]
@Sambit-Mondal 
Merged! Thanks for your contribution.
Regarding your previous pending PR, I’ll create those API keys as soon as I get some free time. I’ll reach out for your assistance once that’s done. In the meantime, feel free to contribute to other issues!

**Comment by vishalverma9572** [comment]
@Sambit-Mondal  you have revealed some of your api keys in firebase.js that's why I have to revert this PR and I am closing this too lease create a new one
Screenshot 2024-10-05 020319

**Comment by Sambit-Mondal** [comment]
@vishalverma9572 I'm really sorry. Okay, I'll fix it by tomorrow and create a new PR. Thanks for informing!

**Comment by vishalverma9572** [comment]
@Sambit-Mondal , No worries, just change your API keys!

**Pull request merged**
